steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=app-engine-oauth-client > src/main/resources/credentials.json" ]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=app-engine-config-js > src/main/webapp/config.js" ]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "appengine:deploy"]
